version: "3"


services:
  node:
    build: .
    restart: always
    environment:
      - NODE_ENV=production 
      - PORT=3012
    ports:
      - "3012:3012"
    volumes:
      - /tmp/dram/:/nfs/groups/beamlines/dram
      # - /users/detector/experiments/:/users/detector/experiments
      - /tmp/zip-service:/home/node/app/files #location of the zipped files
