version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3011:3011"
    volumes:
      - /nfs/offline0/staff:/staff
      - /nfs/offline0/visitors:/visitors
      - /var/lib/zip-service:/home/node/app/files
