version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3011:3011"
    volume:
      - /nfs/offline0/staff:/staff
      - /nfs/offline0/visitors:/visitors
