version: "3"

networks:
  proxy:
    external: true

services:
  node:
    image: "docker.maxiv.lu.se/zip-service"
    user: "2175:1300"
    restart: always
    environment:
      - NODE_ENV=production 
      - PORT=3012
    ports:
      - "3012:3012"
    networks:
      - proxy
    labels:
      - traefik.backend=zip-service
      - traefik.frontend.rule=Host:zip-service.maxiv.lu.se
      - traefik.docker.network=proxy
      - traefik.port=3012
    volumes:
      - /nfs/offline0/staff:/staff
      - /nfs/offline0/visitors:/visitors
      - /tmp/zip-service:/home/node/app/files #location of the zipped files