FROM node:10.16.1-alpine

RUN apk update && apk upgrade

ENV NODE_ENV="production"
ENV PORT=3012
EXPOSE 3012

WORKDIR /home/node/app
COPY package*.json /home/node/app/
COPY .snyk /home/node/app/

RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
RUN npm ci --no-cache

COPY . .

CMD ["npm", "start"]
