version: "3"
services:
  node:
    image: docker pull ghcr.io/scicatproject/zip-service:alpha.1
    restart: no
    ports:
      - "3012:3012"
    volumes:
      - /ess/sims/config/zip-service/config.json:/home/node/app/config.json
      - /tmp/zip-service:/home/node/app/files
      - /users/detector/experiments/:/users/detector/experiments:ro
      - /nfs/groups/beamlines/:/nfs/groups/beamlines:ro
      - /mnt/groupdata/guide_optimizations/:/mnt/groupdata/guide_optimizations:ro
      - /ess/data:/ess/data:ro

