version: "3"


services:
  node:
    build: .
    restart: always
    environment:
      - NODE_ENV=production 
      - PORT=3012
    ports:
      - "3012:3012"
    volumes:
      - /Users/henrikjohansson/zip-service-dev/groups/beamlines/:/nfs/groups/beamlines
      - /Users/henrikjohansson/zip-service-dev/users/detector/experiments/:/users/detector/experiments
      - /Users/henrikjohansson/zip-service-dev/zip-service:/home/node/app/files #location of the zipped files
