version: "3"
services:
  node:
    build: .
    restart: always
    ports:
      - "3012:3012"
    volumes:
      - /nfs/groups/beamlines/:/nfs/groups/beamlines
      - /users/detector/experiments/:/users/detector/experiments
      - /tmp/zip-service:/home/node/app/files #location of the zipped files
